### ISSUE TITLE
Use ChunkFive Ex font

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew.github.io#101]
> With permission of Meredith Mandel, the original author of the ASCII-Font Chunk Five, I have extended Chunk Five Ex to a full featured unicode font with all figures used in latin and cyrillic writing. All latin and cyrillic extensions as well as a lot of letterlike symbols will make this to one of the most complete fonts I offer here.

http://www.dafont.com/chunkfive-ex.font

This should make international font support a lot better.

**Comment by sijad** [comment]
Is this available for using in web browser?

**Comment by mikemcquaid** [comment]
I don't know, I couldn't work it out and don't know much about webfonts.

**Comment by sijad** [comment]
couldn't find any useful information, I guess it not supported to be used in defferent browsers

**Comment by MikeMcQuaid** [comment]
Will consider this in a future redesign.
