### ISSUE TITLE
Use better Font for Arabic and Persian language

### ISSUE THREAD

**Issue by sijad** [Homebrew/homebrew.github.io#105]
current font styles don't seems very good right now
some of font families and font sizes should be changed

**Comment by mikemcquaid** [comment]
I think https://github.com/Homebrew/homebrew.github.io/issues/101 would resolve some of this? Would welcome a PR to use a different font.

**Comment by sijad** [comment]
not sure if that's a good idea,
[Droid Arabic Naskh (Arabic)](https://www.google.com/fonts/earlyaccess) is a better choice I guess

**Comment by MikeMcQuaid** [comment]
Will consider this in a future redesign.
