### ISSUE TITLE
[FEATURE REQUEST] Making website work offline using service workers

### ISSUE THREAD

**Issue by hereisnaman** [Homebrew/homebrew.github.io#184]
I want to work on making website work even offline, using service workers. Showing offline indication on pages and implementing caching patterns based on assets. 

Should I work on this?

**Comment by MikeMcQuaid** [comment]
I'm not sure I see the value. What's the use-case you see for this?

**Comment by hereisnaman** [comment]
It will improve the performance to a great level if we go with cacheFirst pattern with maxAge for cache. As the website don't et update much frequently, we can even set the maxAge to 2days. Fetching content from cache will load the pages really fast.

May be sometime I am reading the docs, I'll be able to read it even offline. People like me who usually read the docs while travelling can be really helped with this, because they don't have a stable connection. They will be able to browse any page they have visited before.

**Comment by MikeMcQuaid** [comment]
The docs on this site (and arguably Homebrew itself) isn't really useful without an internet connection. For the cases where it's not: there is `man brew`. Sorry!

**Comment by j-f1** [comment]
There’s also [the Homebrew docs on DevDocs](https://devdocs.io/homebrew/), which can be downloaded for offline use.
