### ISSUE TITLE
Error: Unknown command: formula-analytics

### ISSUE THREAD

**Issue by Nakilon** [Homebrew/homebrew.github.io#189]
How to run this command myself?
```bash
$ brew formula-analytics --days-ago=365 --json --build-error
Error: Unknown command: formula-analytics
```
The real thing I'm looking for is getting export of more than 1000 items.

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-formula-analytics but you don't have permissions as you aren't a Homebrew maintainer.
