### ISSUE TITLE
The font looks different for latin and not-latin characters

### ISSUE THREAD

**Issue by romcheg** [Homebrew/homebrew.github.io#41]
For non-latic characters that are used in titles this font is not as bold as for latin ones. Since some titles contain both latin and non-latic characters, this looks odd.
![screen shot 2014-10-03 at 16 40 06](https://cloud.githubusercontent.com/assets/214072/4507327/a2f3da52-4b0b-11e4-8097-2e3226346ead.png)
![screen shot 2014-10-03 at 16 40 26](https://cloud.githubusercontent.com/assets/214072/4507328/a2f53a82-4b0b-11e4-8ae3-924c3951eecd.png)

**Comment by mikemcquaid** [comment]
I think this is a WONTFIX I'm afraid due to the desire to maintain our branding with the current font. Sorry!
