### ISSUE TITLE
Font mess

### ISSUE THREAD

**Issue by denpatin** [Homebrew/homebrew.github.io#69]
### Kind of preface
I just decided to open an issue concerning the mess with fonts but it already exists (#41). Though my remarks are a bit different so I open a new issue report.

### Issues core
The issues touch only the titles. There are three cases of representing them:

* Latin script without diacritics (English, _(in our case)_ French, German, etc.) — that's all OK.

* Latin script with diacritics (Polish, Turkish, Spanish, and especially Vietnamese), some cyrillic-script languages (Ukrainian), and neither-latin-nor-cyrillic-script languages (Hebrew, Arabic, etc.) — here, the standard latin letters are in the `ChunkFiveRegular` font, and the rest ones, which are with diacritics, are of `serif` family. It looks very awful:
![polish-bug](https://cloud.githubusercontent.com/assets/1271040/6770641/574abe84-d0d7-11e4-8c6e-16911b56233e.png)
![turkce-bug](https://cloud.githubusercontent.com/assets/1271040/6770642/574b4f0c-d0d7-11e4-9f29-d29e8a6b4ebc.png)
![spanish-bug](https://cloud.githubusercontent.com/assets/1271040/6770640/5749bcdc-d0d7-11e4-88a4-df2b2ed2ba25.png)
![vietnamese-bug](https://cloud.githubusercontent.com/assets/1271040/6770639/5731fe12-d0d7-11e4-8665-fce0b13f5027.png)
![ukrainian-bug](https://cloud.githubusercontent.com/assets/1271040/6770665/0c8d3ff6-d0d8-11e4-889d-efc11b458b15.png)
![japanese-bug](https://cloud.githubusercontent.com/assets/1271040/6770671/41472b8a-d0d8-11e4-892a-c8d90a0097e2.png)

* Some cyrillic-script languages (Russian) and, for some reason, Azerbaijani language — here, `helvetica` is used. It totally differs from the `ChunkFiveRegular` font. No consistency!
![russian-bug](https://cloud.githubusercontent.com/assets/1271040/6770656/bb4d6ee0-d0d7-11e4-834f-b8c980b2c378.png)
![azeri-bug](https://cloud.githubusercontent.com/assets/1271040/6770657/bb4ed76c-d0d7-11e4-9b1f-8c3e533a234f.png)

### Summarizing
For some reason (I haven't yet looked through the HTML/CSS code), different fonts are used.

Generally speaking, my suggestion is the only:

 1. Replace the `ChunkFiveRegular` font with some **really unicode** font so that each character looks identically.

**Comment by mikemcquaid** [comment]
> Replace the ChunkFiveRegular font with some really unicode font so that each character looks identically.

Sorry, that font is part of the Homebrew branding at this stage. I'm up for changing the font in languages where it's necessary but I don't think consistency should mandate it being dropped everywhere.

**Comment by denpatin** [comment]
If so, we need to find a font that is similar to ChunkFiveRegular. Or, at least, add some boldness to the strings in those languages that comprise diacritics and glyph-like characters.

**Comment by mikemcquaid** [comment]
I'm open to any other workarounds.

**Comment by mikemcquaid** [comment]
Passing on this as a WONTFIX as there are no solutions we can see. Sorry!
