### ISSUE TITLE
redcarpet vulnerability

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew.github.io#75]
The risk is very minimal to Homebrew's site, but there's a vulnerability disclosed in Redcarpet and labelled [OSVDB-120415](http://osvdb.org/show/osvdb/120415).

Once Github-Pages and Jeykll have new releases up, we should probably bump.

Discussion upstream at Jeykll is here: https://github.com/jekyll/jekyll/pull/3652.
Discussion upstream at Github is here: https://github.com/github/pages-gem/pull/128

Side-note: The latest Github pages requires Ruby >2.0.0.

**Comment by xu-cheng** [comment]
I believe this can be close. As redcarpet vulnerability doesn't affect Github Pages. (according to the upstream discussion).
