### ISSUE TITLE
SSL Support and short install script URL. 

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew.github.io#76]
Yes, this has been brought up multiple times. (e.g. https://github.com/Homebrew/homebrew/issues/33491). Recently, I do find an easy solution. Sort of?

[Heroku](https://heroku.com) supports SSL custom domain and offers Github integration. If we host https://brew.sh in that platform, we will have the same experience as Github Page and a custom server. 

Using Jekyll and Sinatra to write a small server should be a piece of cake. (I can do this) The only problem would be money. We need to purchase a SSL certificate and I wonder whether Herkuo's free quotas will satisfy our need. (Unless someone can ask for free discount or find other similar free platform. )

**Comment by xu-cheng** [comment]
cc @Homebrew/owners @DomT4

**Comment by DomT4** [comment]
Sounds solid as an idea.

> and a custom server

Do we have control over SSL version/library used, cipher-suites, HSTS, etc? It's not a huge deal, I think most of the maintainers alongside you will actually prefer to know whatever move we make it's not going to beef up their workload even more, but it's a useful point of discussion as to what we have to keep on top of or not.

> We need to purchase a SSL certificate

How much do we want to support? Just the front page, i.e. ` brew.sh ` won't cost more than £8/$13 a year. If we want to cover the `bot.brew.sh` element as well, we'll need to grab two certs or go $$$wildcard. (Unless of course someone donates one to us, or we wait on [Let's Encrypt](https://letsencrypt.org/2014/11/18/announcing-lets-encrypt.html)).

>  I wonder whether Herkuo's free quotas will satisfy our need.

In terms of SSL or does Herkuo impose data usage caps on the free level?

**Comment by xu-cheng** [comment]
It seems Herkuo's SSL addon requires 20$/month. In the meantime, I found another alternative platform OpenShift by Redhat, who offers [free plan for OpenSource Organization](https://www.openshift.com/resource-grants) like us.

**Comment by mikemcquaid** [comment]
I don't want us to move from GitHub Pages to maintaining more code/servers/applications.

**Comment by xu-cheng** [comment]
I understand your concern. But there won't be too many server codes. All need to be done is to link request and static files. Similar to [this one](https://github.com/dommmel/sinatra-jekyll-hybrid/blob/master/sinatra/sinatra_app.rb). Also I'm willing to maintain it if we go down this way.

**Comment by xu-cheng** [comment]
Also, FYI I'm working on the Twitter bot as a side project.

**Comment by mikemcquaid** [comment]
What happens if you get hit by a :bus:? What happens if it ends up costing Homebrew money and we run out of money? I'm really very :-1: on this. With hindsight I wouldn't even have us maintaining our own `bot.brew.sh` servers as it wastes a lot of time that could be spent making Homebrew work better.

I'm also not convinced there's a pressing need for us to have an HTTPS homepage. I'd be surprised if GitHub Pages doesn't offer SSL support some time in the future and that seems like the best thing to wait for.

**Comment by xu-cheng** [comment]
Ok, you do have a point. I think I may get overexcited on new staf I found. (I do find writing bot is kind of fun.)

**Comment by mikemcquaid** [comment]
Thanks. I do think things like e.g. bots are great because if they go down it doesn't really matter to the project or most users as much.

**Comment by DomT4** [comment]
> It seems Herkuo's SSL addon requires 20$/month.

You could host a small ` nginx ` server with full SSL/TLS control, PFS, HSTS, at minimal maintenance for $6 a month. $20 for an addon is steep :confused:

**Comment by DomT4** [comment]
Just to reassure Mike: Not that I'm suggesting we go down the small ` nginx ` server road :wink:.

**Comment by xu-cheng** [comment]
@DomT4  you missed the other half. OpenShift is free.

**Comment by mikemcquaid** [comment]
I'd rather we left this as-is for now and/or used something like CloudFront that doesn't require any code on our part.
